name: プルリクエスト作成時の説明への追加テキストの埋め込み
on:
  pull_request:
    types: [ opened ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Edit Pull Request Description
        run: |
          DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq .body)
          gh pr edit ${{ github.event.pull_request.number }} --body  "${DESCRIPTION}
          
          追加テキスト: ${{ github.event.pull_request.head.ref }}"
